
.PHONY: test clean

# Can't have unused variables 
# Can't have unused parameters 
# No newline at end of file 
CC=gcc
CFLAGS= -g -Wall -pedantic -Werror -Wextra 


OBJS=part1.o

all: part1.o



clean:
	rm -f part1.o

